version: "2"

run:
   timeout: 5m
   tests: false
   modules-download-mode: readonly
output:
   formats:
      text:
         path: stdout
         colors: true
   sort-results: true
linters:
   default: none
   enable:
   - errcheck
   - govet
   - gosec
   - ineffassign
   - staticcheck
   - unused
formatters:
   enable:
   - goimports
   settings:
      goimports:
         local-prefixes: github.com/openshift/lightspeed-operator
issues:
   exclude-dirs:
     - test/