apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/part-of: lightspeed-operator
    control-plane: controller-manager
  name: lightspeed-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      insecureSkipVerify: false
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: lightspeed-operator-controller-manager-service.openshift-lightspeed.svc
  selector:
    matchLabels:
      control-plane: controller-manager
