---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ols-openshift-io-v1alpha1-olsconfig
  failurePolicy: Fail
  name: volsconfig.kb.io
  rules:
  - apiGroups:
    - ols.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - olsconfigs
  sideEffects: None
