#!/usr/bin/env bash
# Shared helpers for operator deployment image args from related_images.json.
set -euo pipefail

image_args::name_to_placeholder() {
	local name="$1"
	printf '__REPLACE_%s__' "$(printf '%s' "$name" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
}

# Emit "name|placeholder|target|flag" for operator deployment patch entries.
image_args::list_patch_entries() {
	local related_images="$1"
	local jqbin="${2:-jq}"

	"${jqbin}" -r '
		[.[] | select(.operator_arg != null)][],
		[.[] | select(.operator_target == "image")][]
		| "\(.name)|\(.operator_target // "args")|\(.operator_arg // "")"
	' "${related_images}" | while IFS='|' read -r name target flag; do
		local placeholder
		placeholder="$(image_args::name_to_placeholder "${name}")"
		printf '%s|%s|%s|%s\n' "${name}" "${placeholder}" "${target}" "${flag}"
	done
}

image_args::generate_deployment_patch() {
	local related_images="$1"
	local output="$2"
	local jqbin="${3:-jq}"

	{
		cat <<'EOF'
# Generated by hack/generate_deployment_patch.sh — do not edit.
# Operand list and CLI flags come from related_images.json (operator_arg / operator_target).
# make deploy and hack/update_bundle.sh substitute placeholders from related_images.json (and IMG for operator).
EOF
		image_args::list_patch_entries "${related_images}" "${jqbin}" | while IFS='|' read -r _ placeholder target flag; do
			if [[ "${target}" == "image" ]]; then
				cat <<EOF
- op: replace
  path: /spec/template/spec/containers/0/image
  value: ${placeholder}
EOF
			else
				cat <<EOF
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --${flag}=${placeholder}
EOF
			fi
		done
	} >"${output}"
}

# Replace placeholders in deployment-patch.yaml from related_images.json.
# operator_img overrides lightspeed-operator when set.
image_args::substitute_deployment_patch() {
	local patch_file="$1"
	local related_images="$2"
	local operator_img="${3:-}"
	local jqbin="${4:-jq}"

	if [[ -n "${operator_img}" ]]; then
		local op_placeholder
		op_placeholder="$(image_args::name_to_placeholder "lightspeed-operator")"
		sed -i "s|${op_placeholder}|${operator_img}|g" "${patch_file}"
		sed -i "/path: \/spec\/template\/spec\/containers\/0\/image/{n;s|value: .*|value: ${operator_img}|}" "${patch_file}"
	fi

	while IFS='|' read -r name placeholder target _; do
		if [[ "${name}" == "lightspeed-operator" ]]; then
			continue
		fi
		local img
		img=$("${jqbin}" -r --arg n "${name}" '.[] | select(.name == $n) | .image' "${related_images}")
		if [[ -n "${img}" && "${img}" != "null" ]]; then
			sed -i "s|${placeholder}|${img}|g" "${patch_file}"
		fi
	done < <(image_args::list_patch_entries "${related_images}" "${jqbin}")
}
