#!/usr/bin/env bash
#
# OLS-3189: Sync agentic CRDs and RBAC from the lightspeed-agentic-operator repo
# at a pinned git ref into the lightspeed-operator bundle.
#
#   * CRDs (agentic.openshift.io_*.yaml) -> config/agentic/crds/
#   * RBAC (manager role/binding, run-approver role/binding, service account)
#     -> config/agentic/   (the v2-only kustomize inputs)
#   * Admission webhook Service/configurations/NetworkPolicy -> config/agentic/
#     (the v2-only serving-certificate and admission contract)
#
# Both land under config/agentic so the v2 kustomize assembly emits them into
# the CSV: operator-sdk ships AND owns the agentic CRDs. (A bundle CRD that is
# not owned by the CSV fails `operator-sdk bundle validate`.)
#
# The synced files must not be hand-edited; re-run this target to update them.
# CRD sync is file-based on purpose: the lightspeed-operator Go module does NOT
# import the agentic-operator API module.
#
# Usage:
#   AGENTIC_OPERATOR_REPO=<git url or path> AGENTIC_OPERATOR_REF=<tag|sha> \
#     ./hack/sync_agentic_manifests.sh
set -euo pipefail

REPO="${AGENTIC_OPERATOR_REPO:?set AGENTIC_OPERATOR_REPO (git URL or local path)}"
REF="${AGENTIC_OPERATOR_REF:?set AGENTIC_OPERATOR_REF (immutable tag or commit SHA)}"

REPO_ROOT="$(git rev-parse --show-toplevel)"
CRD_DEST="${REPO_ROOT}/config/agentic/crds"
RBAC_DEST="${REPO_ROOT}/config/agentic"
GEN_HEADER="# Generated by 'make sync-agentic-crds' from ${REPO} @ ${REF}. DO NOT EDIT."

# Names the agentic RBAC uses in the bundle. The upstream manifests use the
# kustomize-time placeholder __OPERATOR_NAMESPACE__ and the service account name
# "controller-manager"; adapt them to the bundle's concrete names.
OPERATOR_NAMESPACE="openshift-lightspeed"
SA_UPSTREAM="controller-manager"
SA_BUNDLE="lightspeed-agentic-operator-controller-manager"

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

echo "Fetching ${REPO} @ ${REF} ..."
git init -q "${tmp}"
git -C "${tmp}" remote add origin "${REPO}"
git -C "${tmp}" fetch -q --depth 1 origin "${REF}"
git -C "${tmp}" checkout -q FETCH_HEAD

mkdir -p "${CRD_DEST}" "${RBAC_DEST}"

# --- CRDs: glob by group prefix so new agentic CRDs are picked up automatically.
shopt -s nullglob
crds=("${tmp}"/config/crd/bases/agentic.openshift.io_*.yaml)
if [ "${#crds[@]}" -eq 0 ]; then
  echo "error: no agentic.openshift.io_*.yaml CRDs found at ${REF}" >&2
  exit 1
fi
# Validate the complete fixed RBAC set before changing any destination file.
rbac_bases=(role role_binding run_approver_role run_approver_binding service_account)
for base in "${rbac_bases[@]}"; do
  if [ ! -f "${tmp}/config/rbac/${base}.yaml" ]; then
    echo "error: expected RBAC file missing at ${REF}: config/rbac/${base}.yaml" >&2
    exit 1
  fi
done
webhook_bases=(service manifests networkpolicy)
for base in "${webhook_bases[@]}"; do
  if [ ! -f "${tmp}/config/webhook/${base}.yaml" ]; then
    echo "error: expected webhook file missing at ${REF}: config/webhook/${base}.yaml" >&2
    exit 1
  fi
done

for src in "${crds[@]}"; do
  dest="${CRD_DEST}/$(basename "${src}")"
  # Drop a leading '---' document separator before prepending the header: a
  # comment above '---' would parse as an empty leading YAML document, which
  # breaks `operator-sdk bundle validate` and `kustomize build`.
  { echo "${GEN_HEADER}"; sed '1{/^---$/d}' "${src}"; } > "${dest}"
  echo "  CRD  -> ${dest#"${REPO_ROOT}"/}"
done

# Remove CRDs that were generated by a previous sync but have since been
# removed upstream. Without this, removed agentic API types remain in v2 bundles.
for dest in "${CRD_DEST}"/agentic.openshift.io_*.yaml; do
  [ -e "${dest}" ] || continue
  if ! printf '%s\n' "${crds[@]##*/}" | grep -Fxq "$(basename "${dest}")"; then
    rm -f "${dest}"
    echo "  CRD  -X ${dest#"${REPO_ROOT}"/}"
  fi
done

# Regenerate the CRD kustomization so config/agentic can reference the crds/
# directory as a single stable resource (kustomize has no glob support).
{
  echo "${GEN_HEADER}"
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "resources:"
  for dest in "${CRD_DEST}"/agentic.openshift.io_*.yaml; do
    echo "  - $(basename "${dest}")"
  done
} > "${CRD_DEST}/kustomization.yaml"
echo "  CRD  -> ${CRD_DEST#"${REPO_ROOT}"/}/kustomization.yaml"

# --- RBAC: fixed set of files, namespace + service-account name adapted.
for base in "${rbac_bases[@]}"; do
  src="${tmp}/config/rbac/${base}.yaml"
  dest="${RBAC_DEST}/${base}.yaml"
  {
    echo "${GEN_HEADER}"
    if [ "${base}" = "service_account" ] || [ "${base}" = "role_binding" ]; then
      # The service account and its binding subject are the only places the SA
      # name appears; retarget just those to the bundle SA name.
      sed -e "1{/^---$/d}" \
          -e "s/__OPERATOR_NAMESPACE__/${OPERATOR_NAMESPACE}/g" \
          -e "s/name: ${SA_UPSTREAM}\$/name: ${SA_BUNDLE}/" "${src}"
    else
      sed -e "1{/^---$/d}" \
          -e "s/__OPERATOR_NAMESPACE__/${OPERATOR_NAMESPACE}/g" "${src}"
    fi
  } > "${dest}"
  echo "  RBAC -> ${dest#"${REPO_ROOT}"/}"
done

# --- Admission webhooks: retain the upstream serving-cert contract while
# adapting the selector to the OLS-specific agentic manager label.
for base in "${webhook_bases[@]}"; do
  src="${tmp}/config/webhook/${base}.yaml"
  dest="${RBAC_DEST}/webhook_${base}.yaml"
  {
    echo "${GEN_HEADER}"
    sed -e '1{/^---$/d}' \
        -e "s/__OPERATOR_NAMESPACE__/${OPERATOR_NAMESPACE}/g" \
        -e 's/control-plane: controller-manager/control-plane: agentic-controller-manager/g' "${src}"
  } > "${dest}"
  echo "  WEBHOOK -> ${dest#"${REPO_ROOT}"/}"
done

echo "Synced agentic CRDs, RBAC, and admission webhooks from ${REPO} @ ${REF}."
