#!/usr/bin/env bash
# Offline contract test for the pinned Git fetch and manifest adaptation.
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/source/config/crd/bases" "$tmp/source/config/rbac" "$tmp/target/hack"
git -C "$tmp/source" init -q
git -C "$tmp/target" init -q
cp "$root/hack/sync_agentic_manifests.sh" "$tmp/target/hack/"
for name in agenticolsconfigs agenticruns; do
  printf '%s\n' '---' 'kind: CustomResourceDefinition' "name: $name" > "$tmp/source/config/crd/bases/agentic.openshift.io_${name}.yaml"
done
for base in role role_binding run_approver_role run_approver_binding service_account; do
  printf '%s\n' '---' 'namespace: __OPERATOR_NAMESPACE__' 'name: controller-manager' > "$tmp/source/config/rbac/${base}.yaml"
done
git -C "$tmp/source" add .
git -C "$tmp/source" -c user.name=sync-test -c user.email=sync-test@example.com commit -qm initial
export AGENTIC_OPERATOR_REPO="$tmp/source" AGENTIC_OPERATOR_REF=HEAD
export AGENTIC_OPERATOR_COMMIT=$(git -C "$tmp/source" rev-parse HEAD)
script="$tmp/target/hack/sync_agentic_manifests.sh"
(cd "$tmp/target" && bash "$script" > /dev/null)
crd="$tmp/target/config/agentic/crds/agentic.openshift.io_agenticruns.yaml"
role="$tmp/target/config/agentic/role.yaml"
[[ $(grep -c '^  - agentic.openshift.io_' "$tmp/target/config/agentic/crds/kustomization.yaml") == 2 ]]
[[ $(grep -c '^---$' "$crd") == 0 ]] # no leading empty YAML document
[[ $(grep -c '^# Generated by' "$crd") == 1 ]]
grep -q 'namespace: openshift-lightspeed' "$role"
grep -q 'name: lightspeed-agentic-operator-controller-manager' "$tmp/target/config/agentic/service_account.yaml"
grep -q 'name: lightspeed-agentic-operator-controller-manager' "$tmp/target/config/agentic/role_binding.yaml"
old=$(sha256sum "$role")

# Moving the fetch ref must fail before updating any destination file.
printf '%s\n' '# changed' >> "$tmp/source/config/rbac/role.yaml"
rm "$tmp/source/config/crd/bases/agentic.openshift.io_agenticruns.yaml"
git -C "$tmp/source" add -A
git -C "$tmp/source" -c user.name=sync-test -c user.email=sync-test@example.com commit -qm updated
if (cd "$tmp/target" && bash "$script" > /dev/null 2>&1); then
  echo 'sync accepted a source ref that moved past the pinned SHA' >&2
  exit 1
fi
[[ $(sha256sum "$role") == "$old" ]]
export AGENTIC_OPERATOR_COMMIT=$(git -C "$tmp/source" rev-parse HEAD)
(cd "$tmp/target" && bash "$script" > /dev/null)
grep -q '# changed' "$role"
[[ ! -e "$crd" ]]
[[ $(grep -c '^  - agentic.openshift.io_' "$tmp/target/config/agentic/crds/kustomization.yaml") == 1 ]]
echo 'pinned agentic manifest sync contract passed'
