#!/bin/bash
# Helper tool to update the bundle artifacts
# Pre-requisites: opm, make, yq, operator-sdk
# Usage: ./hack/update_bundle.sh -i related_images.json [-v bundle_version]

set -euo pipefail

TEMP_BUNDLE_CONTAINER_FILE=$(mktemp)
DEPLOYMENT_PATCH_FILE="config/default/deployment-patch.yaml"
DEPLOYMENT_PATCH_BACKUP=$(mktemp)
cp "${DEPLOYMENT_PATCH_FILE}" "${DEPLOYMENT_PATCH_BACKUP}"

cleanup() {
  cp "${DEPLOYMENT_PATCH_BACKUP}" "${DEPLOYMENT_PATCH_FILE}"
  rm -f "${TEMP_BUNDLE_CONTAINER_FILE}" "${TEMP_BUNDLE_CONTAINER_FILE}.related_images.json" \
    "${DEPLOYMENT_PATCH_BACKUP}"
}

trap cleanup EXIT

SCRIPT_DIR=$(dirname "$0")

usage() {
  echo "Usage: $0 -i related_images_filename [-v bundle_version] [-c channel_name]"
  echo "  -v bundle_version: The version of the single full bundle (defaults to 1.1.4)"
  echo "  -i related_images_filename: The JSON file containing the related images"
  echo "  -c channel_name: The bundle channel (defaults to alpha)"
  echo "  -h: Show this help message"
}

if [ "$#" -ge 1 ] && [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit 0
fi
BUNDLE_VERSION="${BUNDLE_VERSION:-1.1.4}"
RELATED_IMAGES_FILENAME=""
CHANNEL_NAME="alpha"

while getopts ":v:i:c:h" opt; do
  case "$opt" in
  "v")
    BUNDLE_VERSION=${OPTARG}
    echo "bundle_version is ${BUNDLE_VERSION}"
    ;;
  "i")
    RELATED_IMAGES_FILENAME=${OPTARG}
    if [ ! -f "${RELATED_IMAGES_FILENAME}" ]; then
      echo "related_images_filename ${RELATED_IMAGES_FILENAME} does not exist"
      exit 1
    fi
    echo "related_images from file ${RELATED_IMAGES_FILENAME}"
    ;;
  "c")
    CHANNEL_NAME=${OPTARG}
    echo "channel_name is ${CHANNEL_NAME}"
    ;;
  "h")
    usage
    exit 0
    ;;
  "?")
    echo "Unknown option $OPTARG"
    usage
    exit 1
    ;;
  *)
    echo "Unknown error while processing options"
    exit 1
    ;;
  esac
done

# Supplying BUNDLE_GEN_FLAGS replaces the defaults, but the selected version
# must always be passed exactly once.
BUNDLE_GEN_FLAGS="${BUNDLE_GEN_FLAGS:---channels=${CHANNEL_NAME} --default-channel=${CHANNEL_NAME} -q --overwrite} --version ${BUNDLE_VERSION}"

# Tool check
: ${YQ:=$(command -v yq)}
echo "using yq from ${YQ}"
if [ -z "${YQ}" ]; then
  echo "yq is required"
  exit 1
fi

: ${JQ:=$(command -v jq)}
echo "using jq from ${JQ}"
if [ -z "${JQ}" ]; then
  echo "jq is required"
  exit 1
fi

: ${OPERATOR_SDK:=$(command -v operator-sdk)}
echo "using operator-sdk from ${OPERATOR_SDK}"
if [ -z "${OPERATOR_SDK}" ]; then
  echo "operator-sdk is required"
  exit 1
fi

: ${KUSTOMIZE:=$(command -v kustomize)}
echo "using kustomize from ${KUSTOMIZE}"
if [ -z "${KUSTOMIZE}" ]; then
  echo "kustomize is required"
  exit 1
fi

# This is the only bundle directory consumed by bundle.Dockerfile and Konflux.
BUNDLE_DIR="bundle"
CSV_FILE="${BUNDLE_DIR}/manifests/lightspeed-operator.clusterserviceversion.yaml"
ANNOTATION_FILE="${BUNDLE_DIR}/metadata/annotations.yaml"

BUNDLE_DOCKERFILE="bundle.Dockerfile"

# related_images.json is the single source of truth for (component_name, image)
# pairs. It is required for image and deployment argument substitution.
if [ -n "${RELATED_IMAGES_FILENAME}" ] && [ -f "${RELATED_IMAGES_FILENAME}" ]; then
  echo "using related images from file ${RELATED_IMAGES_FILENAME}"
  RELATED_IMAGES=$(${JQ} '.' "${RELATED_IMAGES_FILENAME}")
else
  echo "error: provide -i related_images.json"
  exit 1
fi

if [ -z "${RELATED_IMAGES}" ] || [ "${RELATED_IMAGES}" = "null" ]; then
  echo "RELATED_IMAGES is empty, please provide related images via -i related_images.json"
  exit 1
fi

OPERATOR_IMAGE=$(${JQ} -r '.[] | select(.name == "lightspeed-operator") | .image' <<<"${RELATED_IMAGES}")
echo "Updating bundle artifacts for image ${OPERATOR_IMAGE:-<from related_images>}"
rm -rf "./${BUNDLE_DIR}"

FILTERED_RELATED_IMAGES_FILE="${TEMP_BUNDLE_CONTAINER_FILE}.related_images.json"
printf '%s\n' "${RELATED_IMAGES}" > "${FILTERED_RELATED_IMAGES_FILE}"
RELATED_IMAGES_FILE="${FILTERED_RELATED_IMAGES_FILE}" ./hack/generate_deployment_patch.sh

${OPERATOR_SDK} generate kustomize manifests -q
${KUSTOMIZE} build config/manifests | ${OPERATOR_SDK} generate bundle ${BUNDLE_GEN_FLAGS} --output-dir "${BUNDLE_DIR}"
# createdAt changes on every generation and is not required in bundle metadata.
${YQ} eval -i 'del(.metadata.annotations.createdAt)' "${CSV_FILE}"
# Replace the Dockerfile generated by operator-sdk and keep its version label
# identical to the CSV, including when a release overrides BUNDLE_TAG.
if [[ ! "${BUNDLE_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]] ||
   ! grep -q '^LABEL version=' "./hack/${BUNDLE_DOCKERFILE}"; then
  echo "invalid bundle version or missing Dockerfile version label: ${BUNDLE_VERSION}" >&2
  exit 1
fi
cp "./hack/${BUNDLE_DOCKERFILE}" "./${BUNDLE_DOCKERFILE}"
sed -i -E "s/^LABEL version=.*/LABEL version=${BUNDLE_VERSION}/" "./${BUNDLE_DOCKERFILE}"
# Substitute deployment args and container image from related_images.json (operator_arg / operator_target).
# shellcheck source=image_args_lib.sh
source "${SCRIPT_DIR}/image_args_lib.sh"
while IFS='|' read -r name placeholder target _; do
  IMG=$(${JQ} -r --arg n "${name}" '.[] | select(.name==$n) | .image' <<<"${RELATED_IMAGES}")
  [ -z "${IMG}" ] || [ "${IMG}" = "null" ] && continue
  IMG_SAFE=$(printf '%s' "${IMG}" | sed 's/"/\\"/g')
  if [ "${target}" = "image" ]; then
    ${YQ} "(.spec.install.spec.deployments[].spec.template.spec.containers[].image |= sub(\"${placeholder}\", \"${IMG_SAFE}\"))" -i ${CSV_FILE}
  else
    ${YQ} "(.spec.install.spec.deployments[].spec.template.spec.containers[].args[] |= sub(\"${placeholder}\", \"${IMG_SAFE}\"))" -i ${CSV_FILE}
  fi
done < <(image_args::list_patch_entries "${FILTERED_RELATED_IMAGES_FILE}" "${JQ}")

# The second controller image is a CSV deployment, not a Classic CLI flag.
AGENTIC_IMAGE=$(${JQ} -er '.[] | select(.name == "lightspeed-agentic-operator") | .image' <<<"${RELATED_IMAGES}")
AGENTIC_IMAGE="${AGENTIC_IMAGE}" ${YQ} eval -i '(.spec.install.spec.deployments[] | select(.name == "lightspeed-agentic-operator-controller-manager").spec.template.spec.containers[] | select(.name == "manager").image) = strenv(AGENTIC_IMAGE)' "${CSV_FILE}"
# Set spec.relatedImages from related_images.json (strip revision and snapshot metadata for OLM CSV).
# The bundle image is only referenced in catalog files, not in the CSV.
RELATED_IMAGES_CSV=$(${JQ} 'map(select(.snapshot_source != "bundle") | del(.revision, .snapshot_component, .snapshot_source, .konflux_prefix, .stable_prefix, .operator_arg, .operator_target))' <<<"${RELATED_IMAGES}")
# set related images to the CSV file
${YQ} eval -i '.spec.relatedImages='"${RELATED_IMAGES_CSV}" ${CSV_FILE}
# add compatibility labels to the annotations file
OCP_VERSIONS=">=v4.16"
${YQ} eval -i '.annotations."com.redhat.openshift.versions"="'"${OCP_VERSIONS}"'"' ${ANNOTATION_FILE}
${YQ} eval -i '(.annotations."com.redhat.openshift.versions" | key) head_comment="OCP compatibility labels"' ${ANNOTATION_FILE}
${YQ} eval -i '.annotations."features.operators.openshift.io/fips-compliant"="true"' ${ANNOTATION_FILE}

# Validate the final artifact, after image, related-image, and annotation updates.
${OPERATOR_SDK} bundle validate "./${BUNDLE_DIR}"

echo "Finished running $(basename "$0")"
